name: about
description: Displays an About dialog, which describes the application, can show licenses, changelog, and other information.
homepage: https://github.com/DavBfr/flutter_about
version: 2.1.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.1
  markdown: ^7.2.2
  path: ^1.9.0
  simple_mustache: ^2.1.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
